name: "Tests: Integration"

run-name: "Integration [${{ github.event.workflow_run.head_branch }}]: ${{ github.event.workflow_run.head_commit.message }}"

on:
  workflow_dispatch:
    inputs:
      workflow:
        description: Tests to run
        required: true
        type: choice
        options:
          - all
          - run-integration-tests-cf-env
          - run-integration-tests-cf-env-with-client-creds
          # - run-integration-tests-cf-env-with-min-capi
          - run-cats-cf-env
  push:
    tags:
      - "v9.*"
      - "v8.*"
      - "v7.*"
  pull_request_target:
    branches:
      - main
      - v9
      - v8
      - v7
    paths-ignore:
      - "doc/**"
      - ".gitpod.yml"
      - "README.md"
jobs:
  get-sha:
    runs-on: ubuntu-latest
    outputs:
      gitRef: ${{steps.calculate.outputs.ref}}
    steps:
      - id: calculate
        run: |
          if [[ ${{ github.event_name == 'pull_request_target' }} ]]; then
            echo "::set-output name=ref::${{ github.event.pull_request.head.sha }}"
          elif [[ ${{ github.event_name == 'push' }} ]]; then
            echo "::set-output name=ref::${{ github.event.push.after }}"
          else
            echo "::set-output name=ref::${{github.event.workflow_run.head_sha}}"
          fi
  units:
    name: Units
    runs-on: ubuntu-latest
    needs:
      - get-sh
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ job.get-sha.gitRef }}
      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Run Units
        run: make units
  run-integration-tests-cf-env:
    name: Integration tests
    needs:
      - get-sh
      - units
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.workflow == 'all' || inputs.workflow == 'run-integration-tests-cf-env' }}
    uses: ./.github/workflows/tests-integration-reusable.yml
    with:
      capi-version: edge
      run-with-client-creds: false
      os: ubuntu-latest
      name: Integration
      gitRef: ${{needs.get-sha.outputs.gitRef}}
    secrets: inherit

  run-integration-tests-cf-env-with-client-creds:
    name: client creds
    needs:
      - get-sh
      - units
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.workflow == 'all' || inputs.workflow == 'run-integration-tests-cf-env-with-client-creds' }}
    uses: ./.github/workflows/tests-integration-reusable.yml
    with:
      capi-version: edge
      run-with-client-creds: true
      os: ubuntu-latest
      name: Integration client creds
      gitRef: ${{needs.get-sha.outputs.gitRef}}
    secrets: inherit

  # run-integration-tests-cf-env-with-min-capi:
  #   name: MIN CAPI
  #   needs:
  #     - get-sh
  #     - units
  #   if: ${{ github.event_name != 'workflow_dispatch' || inputs.workflow == 'all' || inputs.workflow == 'run-integration-tests-cf-env-with-min-capi' }}
  #   uses: ./.github/workflows/tests-integration-reusable.yml
  #   with:
  #     capi-version: min
  #     run-with-client-creds: false
  #     os: ubuntu-latest
  #     name: Integration MIN CAPI
  #     pool-name: cfd_16_11_0
  #     pool-namespace: tas-devex
  #     is-pr: ${{ github.event_name != 'workflow_dispatch' }}
  #   secrets: inherit

  run-cats-cf-env:
    name: CATS
    needs:
      - get-sh
      - run-integration-tests-cf-env
      - run-integration-tests-cf-env-with-client-creds
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.workflow == 'all' || inputs.workflow == 'run-cats-cf-env' }}
    uses: ./.github/workflows/tests-integration-reusable.yml
    with:
      capi-version: edge
      run-with-client-creds: false
      os: ubuntu-latest
      name: cats
      gitRef: ${{needs.get-sha.outputs.gitRef}}
    secrets: inherit
